# Generated by Django 3.1.5 on 2021-03-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='company',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
